### ISSUE TITLE
Undefined symbols on macOS:   _re_compile_pattern

### ISSUE THREAD

**Issue by fatso83** [AdaCore/spawn#35]
I first tried using Alire to get this library when building GNAT Studio, but it failed:
```
❯ alr get --build spawn_glib
ⓘ Deploying gtkada=25.0.1...
         -=O=-   #      #       #       #
                                                                                                                                                                                                                                                ⓘ Running post-fetch actions for gtkada=25.0.1...
checking build system type... x86_64-apple-darwin24.1.0
checking host system type... x86_64-apple-darwin24.1.0
checking target system type... x86_64-apple-darwin24.1.0
checking for pkg-config... /opt/gcc-14.2.0-3-aarch64/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/Users/carlerik/.local/share/alire/builds/gtkada_25.0.1_d3787772/05561da954afaee17128f59bba699db2f2e4a4215317b2b818a8016192c82334':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
error: Command ["bash", "-c", "PATH=${DISTRIB_ROOT}/mingw64/bin:${PATH} ./configure"] exited with code 1
```

The exact error could be found in the `config.log` output
<details>
<pre>
configure:5745: checking for re_compile_pattern
configure:5745: gcc -o conftest  -I/opt/homebrew/opt/postgresql@15/include -L/opt/homebrew/opt/postgresql@15/lib conftest.c  >&5
Undefined symbols for architecture arm64:
  "_re_compile_pattern", referenced from:
      _main in ccz7Z97C.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
configure:5745: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNAT Studio"
| #define PACKAGE_TARNAME "gnat-studio"
| #define PACKAGE_VERSION "0.0"
| #define PACKAGE_STRING "GNAT Studio 0.0"
| #define PACKAGE_BUGREPORT "report@adacore.com"
| #define PACKAGE_URL ""
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_PYTHON "3.11"
| /* end confdefs.h.  */
| /* Define re_compile_pattern to an innocuous variant, in case <limits.h> declares re_compile_pattern.
|    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
| #define re_compile_pattern innocuous_re_compile_pattern
| 
| /* System header to define __stub macros and hopefully few prototypes,
|    which can conflict with char re_compile_pattern (); below.  */
| 
| #include <limits.h>
| #undef re_compile_pattern
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char re_compile_pattern ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined __stub_re_compile_pattern || defined __stub___re_compile_pattern
| choke me
| #endif
| 
| int
| main (void)
| {
| return re_compile_pattern ();
|   ;
|   return 0;
| }
configure:5745: result: no
configure:5754: checking for sys/stropts.h
configure:5754: gcc -c  -I/opt/homebrew/opt/postgresql@15/include conftest.c >&5
conftest.c:48:10: fatal error: sys/stropts.h: No such file or directory
   48 | #include <sys/stropts.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
configure:5754: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNAT Studio"
| #define PACKAGE_TARNAME "gnat-studio"
| #define PACKAGE_VERSION "0.0"
| #define PACKAGE_STRING "GNAT Studio 0.0"
| #define PACKAGE_BUGREPORT "report@adacore.com"
| #define PACKAGE_URL ""
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_PYTHON "3.11"
| /* end confdefs.h.  */
| #include <stddef.h>
| #ifdef HAVE_STDIO_H
| # include <stdio.h>
| #endif
| #ifdef HAVE_STDLIB_H
| # include <stdlib.h>
| #endif
| #ifdef HAVE_STRING_H
| # include <string.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| #include <sys/stropts.h>
configure:5754: result: no
configure:5762: checking for openpty in -lutil
configure:5785: gcc -o conftest  -I/opt/homebrew/opt/postgresql@15/include -L/opt/homebrew/opt/postgresql@15/lib conftest.c -lutil   >&5
configure:5785: $? = 0
configure:5795: result: yes
configure:5961: ------------- Summary for GNAT Studio --------------------
configure:5963:  GNATcoll: 
configure:5965:  Xml/Ada: with_xmlada
configure:5967:     use ADA_PROJECT_PATH to find xmlada.gpr
configure:5969: --------------------------------------------------
configure:6124: creating ./config.status
</pre>
</details>

So both a linking error (`Undefined symbols for architecture arm64:  "_re_compile_pattern"`)  and a missing header (`conftest.c:48:10: fatal error: sys/stropts.h: No such file or directory`) seems to be issues.


I then tried cloning the repo and building per the install docs, but that did not work either and this time there was no config.log!
```
spawn/packages/glib on  master [!] on ☁️  (eu-north-1) on ☁️
✦ ❯ alr build
ⓘ Running post-fetch actions for gtkada=23.0.0...
checking build system type... x86_64-apple-darwin24.1.0
checking host system type... x86_64-apple-darwin24.1.0
checking target system type... x86_64-apple-darwin24.1.0
checking for pkg-config... /opt/gcc-14.2.0-3-aarch64/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/Users/carlerik/.local/share/alire/builds/gtkada_23.0.0_bac4d634/05561da954afaee17128f59bba699db2f2e4a4215317b2b818a8016192c82334':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
error: Command ["bash", "-c", "PATH=${DISTRIB_ROOT}/mingw64/bin:${PATH} ./configure"] exited with code 1
```

**Comment by fatso83** [comment]
I just found ONE single reference that is identical: [findutils 4.8.0 fails to build on macOS 10.14, 10.15, 11.1
](https://lists.nongnu.org/archive/html/bug-findutils/2021-01/msg00053.html)

**Comment by reznikmm** [comment]
you need have consistent alire, toolchain and libraries. If you on AArch64 then install Alire for ARM64, it will install GNAT for ARM64 (not x86_64 as you have now).

https://github.com/alire-project/alire/releases/download/v2.0.2/alr-2.0.2-bin-aarch64-macos.zip

(See [Alire release page](https://github.com/alire-project/alire/releases/tag/v2.0.2). Or you can use "universal" binary from Alire [nightly build release](https://github.com/alire-project/alire/releases/tag/nightly).

PS. Building GNAT Studio is a tedious process. I would suggest to download binary release instead.

**Comment by fatso83** [comment]
I was both unaware that Alire had ARM builds until tonight (was mentioned in alire-project/alire#1828), as it is not mentioned in the Downloads section on the hompage, and also that there were binary releases available (mentioned in [this thread on Reddit](https://www.reddit.com/r/ada/comments/1i83zjf/comment/m8t6jeu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) about building it). 

Anyway, the latest binary release of GNAT Studio fails on my machine, as well, and `alr build` still fails, now with another error 🤷  I will stop digging now, I think 😄
